# Main navigation

[[main]]
  name = "Rétrospectives"
  url = "/galleries"
  weight = 1

[[main]]
 name = "Qui sommes-nous ?"
 url = "/a-propos"
 weight = 4

[[main]]
 name = "Édition 2026"
 url = "/edition-2026"
 weight = 2

[[main]]
 name = "Partenaires 2026"
 url = "/edition-2026/partenaires"
 weight = 3

[[main]]
  name = "Contact"
  url = "/contact"
  weight = 5


# Quick navigation (footer)

[[quick]]
  name = "Participer"
  url = "/participer"
  weight = 30

[[quick]]
  name = "Contact"
  url = "/contact"
  weight = 50

# Informative links

[[infos]]
  name = "Dossier presse"
  url = "/a-propos"
  weight = 10

[[infos]]
  name = "Mentions légales"
  url = "/mentions-legales"
  weight = 10

[[infos]]
  name = "Statuts de l'association"
  url = "/statuts"
  weight = 20

[[infos]]
  name = "Ligne politique"
  url = "/ligne-politique"
  weight = 30

[[infos]]
  name = "Sexualité et protection"
  url = "https://www.sexosafe.fr/"
  weight = 40

# Social links

[[social]]
  name = "Facebook"
  url = "https://www.facebook.com/GrenoblePride/"
  weight = 10

[[social]]
  name = "Instagram"
  url = "https://www.instagram.com/GrenoblePride/"
  weight = 20
